apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  template:
    spec:
      volumes:
      - name: spinnaker-monitoring-registry-volume
        secret:
          secretName: spinnaker-monitoring-registry-echo
